# Generated by Django 5.2.12 on 2026-04-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
    ]
