# Generated by Django 5.2.12 on 2026-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rebuild_admin_logentry_with_uuid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
