# Generated by Django 5.2.12 on 2026-04-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('users', '0004_permission_is_active_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='shop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='shop.shop'),
            preserve_default=False,
        ),
    ]
