# Generated by Django 5.2.12 on 2026-05-01

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_branch_remove_user_role_remove_user_shop_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopmembership',
            name='unique_membership_per_shop',
        ),
        migrations.AddConstraint(
            model_name='shopmembership',
            constraint=models.UniqueConstraint(
                fields=('user', 'shop', 'role'),
                condition=Q(branch__isnull=True),
                name='unique_shop_level_membership_per_user_role',
            ),
        ),
        migrations.AddConstraint(
            model_name='shopmembership',
            constraint=models.UniqueConstraint(
                fields=('user', 'shop', 'role', 'branch'),
                condition=Q(branch__isnull=False),
                name='unique_branch_membership_per_user_role_branch',
            ),
        ),
    ]